Movie.create(emojis: "🔕 🐏 🐏 🐏 ", answer: "Le silence des agneaux" )
Movie.create(emojis: "👦 👧 🌂 👜 🇬🇧", answer: "Mary Poppins" )
Movie.create(emojis: "👨 💬 🐴 ", answer: "L'homme qui murmurait à l'oreille des chevaux" )
Movie.create(emojis: "👮 📮 👴 📝", answer: "Bienvenu chez les ch'tis" )
Movie.create(emojis: "💭 📝 👘", answer: "MéMoires d'une Geïsha" )
Movie.create(emojis: "👨 👨 ⛺ 🗻 ", answer: "Le secret de Brokeback mountain" )
Movie.create(emojis: "🐦 🐦 🐦 🐦 📄", answer: "Vaillant" )
Movie.create(emojis: "🔫 🔍 👨 🎩", answer: "Sherclock Holmes" )
Movie.create(emojis: "👳 📺 💵 💵 ", answer: "Slumdog millionaire" )
Movie.create(emojis: "🐭 🚗", answer: "Stuart Litte" )
Movie.create(emojis: "👽 ☝️ ☎️ 🏠", answer: "ET" )
Movie.create(emojis: "👀 👅 👂 ✋ 👃 6️⃣ ", answer: "Sixième Sens" )
Movie.create(emojis: "🎈 🏡 👴 👦 ", answer: "Là-haut" )
Movie.create(emojis: "🐻 ❤ 🍻 » 🚬", answer: "Mr and Mrs Smith" )
Movie.create(emojis: "🛀 🔪 ", answer: "Psychose" )
Movie.create(emojis: "⏰ 📆 ⏰ 📆 ⏰ 📆 ⏰ 📆", answer: "Un jour sans fin" )
Movie.create(emojis: "😈 👗 👠 ", answer: "Le diable s'habille en Prada" )
Movie.create(emojis: "💻 💊", answer: "Matrix" )
Movie.create(emojis: "👻 👻 🔫", answer: "Ghost Buster" )
Movie.create(emojis: "👦 👐 ✂ ✂ ", answer: "Edouard aux mains d'argent" )
Movie.create(emojis: "💍 💍 💍 💍 💀 ", answer: "4 mariages et un enterrement" )
Movie.create(emojis: " 🌊 👈 ", answer: "La Vague" )
Movie.create(emojis: " 💃 🐺 🐺 ", answer: "Danse avec les loups" )
Movie.create(emojis: " 🔓 🐬 ", answer: "Sauvez Willy" )
Movie.create(emojis: " 💩 💃  ", answer: "Dirty Dancing" )
Movie.create(emojis: " 👳 🚣 🐅 ", answer: "L'odyssée de Pi" )
Movie.create(emojis: " 🎅🏻 🗑 ", answer: "Le Père Noël est une ordure" )
Movie.create(emojis: " 👨‍👩‍👧‍👦 🏠 🐒 🎲 🦏 ", answer: "Jumanji" )
Movie.create(emojis: " 🧑🏼 👴🏻 🚗 💨 🔙 ", answer: "Retour vers le futur" )
Movie.create(emojis: " 🍫 🎫  ", answer: "Charlie et la chocolaterie" )
Movie.create(emojis: " 👩🏼 🐰 🕰 🕳 ", answer: "Alice au pays des merveilles" )
Movie.create(emojis: " 🏝 🏐 🖐🏻 ", answer: "Seul au monde" )
Movie.create(emojis: " 🦈 🦷 🌊 ", answer: "Les dents de la mer" )
Movie.create(emojis: "  🧍🏼‍♂️ 🚀 🪐➡️ ❌ 🌍 ", answer: "Interstellar" )
Movie.create(emojis: "  👩‍❤️‍👨 🔙 ❄️ 🏓 ", answer: "Mon inconnue" )
Movie.create(emojis: " 🌍 🐵 🐵 ", answer: "La planète des singes" )
Movie.create(emojis: " 👴🏻 🔜 👱🏻‍♂️ 🔜 👦🏼 🔜 👶🏼 ", answer: "L'étrange histoire de Benjamin Button" )
Movie.create(emojis: " 👩 ⚔️ 🩸 🩸 ⛩️ ", answer: "Kill Bill" )
Movie.create(emojis: " 🛫 👨🏻‍✈️ ⁉️ ", answer: "Y a-t-il un pilote dans l'avion" )
Movie.create(emojis: " 👩🏻 ➡️ 🧑🏻 ⚔️ 🐉 ", answer: "Mulan" )
Movie.create(emojis: " ◼️ 🦢 🩰 ", answer: "Black Swan" )
Movie.create(emojis: " 👨‍👩‍👧‍👦 💰 🏰 🍟 ", answer: "Les Tuches" )
Movie.create(emojis: " 🧹 👨🏼‍🏫 🧠 🗣️ ", answer: "Will Hunting" )
Movie.create(emojis: " 🧼 🤜🏻 ", answer: "Fight Club" )
Movie.create(emojis: " 🚶 🏃 ✈️ ", answer: "Attrape moi si tu veux" )
